src/Entity/ProductCategory.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductCategoryRepository")
 */
class ProductCategory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updated_by;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="category")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?User $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Form/ProductCategoryType.php
<?php

namespace App\Form;

use App\Entity\ProductCategory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Unique;

class ProductCategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez entrer un nom'
                    ])
                ]
            ])

            // Bouton Envoyer
            ->add('submit', SubmitType::class, array(
                'label' => 'Enregistrer'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ProductCategory::class,
        ]);
    }
}

src/Controller/ProductCategoryController.php
<?php

namespace App\Controller;

use App\Entity\ProductCategory;
use App\Entity\DataSearch;
use App\Form\ProductCategoryType;

use Symfony\Component\HttpFoundation\Request;

class ProductCategoryController extends MasterController
{
    /**
     * Affichage de la page recensant les catégories de produits
     * 
     * @param   Request     $request    Requête HTTP
     * 
     * @return  Response
     */
    public function index(Request $request){
        $this->denyAccessUnlessGranted(array('ROLE_VENDEUR'));

        // Récupérer toutes les catégories de produits
        $search     = $this->getProductCategoryService()->getProductCategorySearch();
        // On instancie le formulaire de recherche
        $form       = $this->getSearchForm($request, $search);

        $categories = $this->getProductCategoryService()->getProductCategories($search);

        $parameters = array(
            'form'          => $form->createView(),
            'categories'    => $categories
        );

        return $this->render('productCategory/index.html.twig', $parameters);
    }

    /**
     * Ajout / Édition d'une catégorie
     * 
     * @param   Request     $request    Requête HTTP
     * @param   int         $id         Identifiant
     * 
     * @return  Response
     */
    public function edit(Request $request, int $id=null){
        $this->denyAccessUnlessGranted(array('ROLE_VENDEUR'));

        if($id) {
            $mode       = 'update';

            $search     = $this->getProductCategoryService()->getProductCategorySearch($id);
            $category   = $this->getProductCategoryService()->getProductCategories($search)[0];
        }
        else {
            $mode       = 'new';

            $category   = new ProductCategory();
        }

        $form       = $this->createForm(ProductCategoryType::class, $category);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->saveProductCategory($category, $mode);

            return $this->redirectFormToRoute('app_product_category_edit', array('id' => $category->getId()));
        }

        $parameters = array(
            'form'  => $form->createView(),
            'cat'   => $category,
            'mode'  => $mode
        );

        return $this->render('productCategory/edit.html.twig', $parameters);
    }

    /**
     * Compléter la catégorie avec des informations avant enregistrement
     * 
     * @param   ProductCategory     $category
     * @param   string              $mode 
     * 
     * @return ProductCategory
     */
    private function completeProductCategoryBeforeSave(ProductCategory $category, string $mode) {
        if($mode == 'new'){
            $category->setCreatedAt(new \DateTime());
            $category->setCreatedBy($this->getUser());
        }
        $category->setUpdatedAt(new \DateTime());
        $category->setUpdatedBy($this->getUser());

        return $category;
    }

    /**
     * Enregistrer une catégorie en base de données
     * 
     * @param   ProductCategory     $category
     * @param   string              $mode 
     */
    private function saveProductCategory(ProductCategory $category, string $mode){
        $category = $this->completeProductCategoryBeforeSave($category, $mode);
        
        $em = $this->getDoctrine()->getManager();
        $em->persist($category);
        $em->flush();
        $this->addFlash('success', 'Enregistré avec succès');
    }
}

templates/productCategory/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégories de produits{% endblock %}

{% block body %}
    {#{ dump(form) }#}

    {# Titre de la page #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{% if mode == 'new' %}Ajout{% else %}Modification{% endif %} - Catégories de produits</h1>
        </div>
    </div>

    <div class="container">
        {{ form_start(form, {'method': 'POST', 'attr': {'novalidate': 'novalidate' }} ) }}

        {# ------------------------- #}
        {#      INFOS GÉNÉRALES      #}
        {# ------------------------- #}
        {% if mode == 'update' %}
        <div class="panel-heading" >
            <h4 class="panel-title" id="contact-panel-title">
                <a data-group data-toggle="collapse" href="#info">{{ include('helpers/icon/_fa.html.twig', {'icon': 'angle-double-down'}) }} Informations générales</a>
            </h4>
        </div>
        {% endif %}

        <div id="info" class="panel-collapse {% if mode == 'update' %}collapse{% endif %}">
            {{ include('helpers/form/_group.html.twig', {
                        'field': form['name']
                    }) }}
        </div>

        {# -------------------------------- #}
        {#      INFOS COMPLÉMENTAIRES       #}
        {# -------------------------------- #}
        
        {% if mode == 'update' %}
        <div class="panel-heading" >
            <h4 class="panel-title">
                <a data-group data-toggle="collapse" href="#info-compl">{{ include('helpers/icon/_fa.html.twig', {'icon': 'angle-double-down'}) }} Informations complémentaires</a>
            </h4>
        </div>
        <div id="info-compl" class="panel-collapse collapse table-responsive">
            <table class="table table-condensed fiche">
                <tbody>
                    <tr>
                        <td>Création</td>
                        <td>    
                            Créé le {{ cat.createdAt | date("d-m-Y à H:i:s") }}
                            {{ cat.createdBy?'par ' ~ cat.createdBy.username }}
                        </td>  
                    </tr>
                    <tr>
                        <td>Modification</td>
                        <td>    
                            Modifié le {{ cat.updatedAt | date("d-m-Y à H:i:s") }}
                            {{ cat.updatedBy?'par ' ~ cat.updatedBy.username }}
                        </td>  
                    </tr>
                </tbody>
            </table>
        </div>
        {% endif %}

        <div class="row">
            {% if not form.vars.valid %}
            <div class="col-md-8 error">
                {{ include('helpers/icon/_fa.html.twig', {'icon': 'exclamation-triangle'}) }} 
                Le formulaire contient des erreurs. Vérifiez les différentes rubriques.
            </div>
            {% else %}
                <div class="col-md-8"></div>
            {% endif %} 
            <div class="col-md-4 text-right">
                {{ form_widget(form.submit, { 'attr': {'class': 'btn btn-info'} }) }}
            </div>
        </div>

        {{ form_widget(form) }}

        {{ form_end(form) }}

    </div>

{% endblock %}

{% block stylesheets %}
    <style>
        .container{
            width: 100%;
            border: 1px solid #ddd;
            padding-top: 13px;
            border-radius: 10px;
            background-color: #F9F9FA;
            color: #413C49;
            margin-top: 20px;
            padding-bottom: 13px;
        }

        .error{
            color: red;
            font-weight: 600;
        }

        .has-error ul{
            color: red;
            list-style-type: none;
            padding-left: 0;
            padding-top: 5px;
            font-style: italic;
        }

        .btn-lg{
            color: #fff;
            margin: auto;
            margin-top: 30px;
        }
    </style>
{% endblock %}

templates/productCategory/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégories de produits{% endblock %}

{% block body %}
    {#{ dump(form) }#}

    {# Titre de la page #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Listing - Catégories de produits</h1>
        </div>
    </div>

    {# Barre de recherche #}
    {{ include('helpers/form/_search.html.twig', { 
                'fields':     ['whatever', 'product_category'] }) }}

    <div class="row alert alert-warning" role="alert">
        <div class="col-xs-9 col-sm-10"></div>

        <div class="col-xs-3 col-sm-2">
            <a href="{{ path('app_product_category_add') }}" role="button" class="btn btn-info text-right">
                {{ include('helpers/icon/_fa.html.twig', {'icon': 'plus'}) }} Ajouter
            </a>
        </div>
    </div>

    <div class="container-fluid">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Créé le</th>
                    <th scope="col">Modifié le</th>
                    <th scope="col">{# Bouton d'action #}</th>
                </tr>
            </thead>
            <tbody>
                {% for cat in categories %}
                <tr>
                    <th scope="row">
                        {{ cat.id }}
                    </th>
                    <td>
                        {{ cat.name }}
                    </td>
                    <td>
                        {{ cat.createdAt | date("d-m-Y à H:i:s") }}
                    </td>
                    <td>
                        {{ cat.updatedAt | date("d-m-Y à H:i:s") }}
                    </td>
                    <td>
                        <a href="{{ path('app_product_category_edit', {'id': cat.id}) }}" role="button" class="btn btn-info">Modifier</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block stylesheets %}

{% endblock %}