src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="orders")
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="bigint")
     */
    private $reference;

    /**
     * @ORM\Column(type="json")
     */
    private $products = [];

    /**
     * @ORM\Column(type="float")
     */
    private $total_ht;

    /**
     * @ORM\Column(type="float")
     */
    private $total_ttc;

    /**
     * @ORM\Column(type="float")
     */
    private $tva;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="orders")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id", nullable=false)
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updated_by;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getProducts(): ?array
    {
        return unserialize($this->products);
    }

    public function setProducts(array $products): self
    {
        $this->products = serialize($products);

        return $this;
    }

    public function getTotalHt(): ?float
    {
        return $this->total_ht;
    }

    public function setTotalHt(float $total_ht): self
    {
        $this->total_ht = $total_ht;

        return $this;
    }

    public function getTotalTtc(): ?float
    {
        return $this->total_ttc;
    }

    public function setTotalTtc(float $total_ttc): self
    {
        $this->total_ttc = $total_ttc;

        return $this;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): self
    {
        $this->tva = $tva;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?User $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Order;
use App\Entity\DataSearch;
use App\Form\ProductType;

use Symfony\Component\HttpFoundation\Request;

class OrderController extends MasterController
{
    /**
     * Affichage de la page recensant les produits
     * 
     * @param   Request     $request    Requête HTTP
     * 
     * @return  Response
     */
    public function index(Request $request){
        $this->denyAccessUnlessGranted(array('ROLE_VENDEUR'));

        // Récupérer tous les produits
        $search     = $this->getOrderService()->getOrderSearch();
        // On instancie le formulaire de recherche
        $form       = $this->getSearchForm($request, $search);

        $orders     = $this->getOrderService()->getOrders($search);

        $parameters = array(
            'form'      => $form->createView(),
            'orders'    => $orders
        );

        return $this->render('order/index.html.twig', $parameters);
    }

    /**
     * Ajout / Édition d'une produit
     * 
     * @param   Request     $request    Requête HTTP
     * @param   int         $ref        Référence
     * 
     * @return  Response
     */
    public function listDetails(Request $request, int $ref=null){
        $this->denyAccessUnlessGranted(array('ROLE_VENDEUR'));

        $search = $this->getOrderService()->getOrderSearch($ref);
        $order  = $this->getOrderService()->getOrders($search);

        $parameters = array(
            'order'     => $order[0],
            'products'  => $order[0]->getProducts()
        );

        return $this->render('order/liste.html.twig', $parameters);
    }
}

src/Controller/WebService/OrderController.php
<?php

namespace App\Controller\WebService;

use App\Entity\Order;
use App\Entity\User;
use App\Entity\Product;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class OrderController extends MasterController 
{
    /**
     * Mailer
     */
    protected $mailer;

    /**
     * Constructeur
     */
    public function __construct(\Swift_Mailer $mailer)
    {
        $this->mailer = $mailer;
    }
    

    /**
     * Récupérer les informations de l'utilisateur authentifié
     * 
     * @param   Request     $request    Requête HTTP
     * 
     * @return  Response
     */
    public function buy(Request $request){
        $user = $this->getUser();
        // Array contenant toutes les données reçues via la requête HTTP
        $data = json_decode($request->getContent(), true);

        try {
            
            $products   = $this->getRepository('App:Product')->findBy(['reference' => $data['references']]);
            $arrFinal   = array();
            $total_ttc  = 0;
            $i          = 0;

            // Mise à jour des quantités de chaque produit
            foreach($products as $product){
                $arr    = array();
                $qte    = $product->getQuantity() - intval($data['quantities'][$i]);
                $product->setQuantity($qte);

                // On enregistre le produit en BDD
                $this->saveProduct($product);

                $arr['product']     = $product;
                $arr['quantity']    = $data['quantities'][$i];
                array_push($arrFinal, $arr);

                $total_ttc += $product->getPrice() * $data['quantities'][$i];
                $i += 1;
            }

            // On vérifie le solde de l'utilisateur 
            if($user->getAccount() < $total_ttc){
                return new JsonResponse([
                    'code'          => 401,
                    'message'       => 'Solde insuffisant'
                ]);
            }
            else {
                $newAccount = intval($user->getAccount()) - $total_ttc;
                $user->setAccount($newAccount);
                
                $order = new Order();
                $order->setProducts($arrFinal);
                $order->setReference(random_int(10000000, 19999999));
                $order->setTotalTtc($total_ttc);
                $order->setTotalHt($total_ttc / 1.2);
                $order->setTva(0.2);

                // Enregistrement de la commande
                $this->saveOrder($order, 'new');
                // Mise à jour de l'utilisateur
                $this->saveUser($user);

                // Email de confirmation
                $params = [
                    'user'      => $user,
                    'products'  => $arrFinal,
                    'quantity'  => $data['quantities'],
                    'order'     => $order
                ];
                $this->sendMail($user, 'Confirmation d\'achat', 'emails/order_confirmation.html.twig', $params, $this->mailer);

                return new JsonResponse([
                    'code'          => 200,
                    'references'    => sizeof($arrFinal),
                    'message'       => 'OK ! Achat effectué'
                ]);
            }
            
        } catch(\Exception $e){
            return new JsonResponse([
                'code'          => 500,
                'message'       => 'Une erreur interne est survenue',
                'erreur'        => $e->getMessage()
            ]);
        }
    }

    /**
     * Lister les commandes utilisateur
     * 
     * @param   Request     $request    Requête HTTP
     * 
     * @return  Response
     */
    public function listOrders(Request $request){
        $user   = $this->getUser();

        try{
            $orders = $user->getOrders();
            $refs   = array();

            foreach($orders as $order){
                array_push($refs, $order->getReference());
            }

            return new JsonResponse([
                'code'          => 200,
                'references'    => $refs,
            ]);
        } catch(\Exception $e){
            return new JsonResponse([
                'code'          => 500,
                'message'       => 'Une erreur interne est survenue',
                'exception'     => $e->getMessage()
            ]);
        }
    }

    /**
     * Récupérer une commande
     * 
     * @param   Request     $request    Requête HTTP
     * @param   int         $ref        Référence
     * 
     * @return  Response
     */
    public function getOrder(Request $request, int $ref){
        try{
            $order  = $this->getRepository('App:Order')->findOneBy(['reference' => $ref]);
            $arr    = array();
            $i      = 0;

            $arr                        = array();
            $arr['reference']           = $ref;
            $arr['total']               = $order->getTotalTtc();
            $arr['product_names']       = array();
            $arr['product_quantities']  = array();
            $arr['product_prices']      = array();
            foreach($order->getProducts() as $pr){
                array_push($arr['product_names'], $pr['product']->getName());
                array_push($arr['product_prices'], $pr['product']->getPrice());
                array_push($arr['product_quantities'], $pr['quantity']);
                
                $i += 1;
            }

            return new JsonResponse([
                'code'  => 200,
                'order' => $arr,
            ]);
        } catch(\Exception $e){
            return new JsonResponse([
                'code'          => 500,
                'message'       => 'Une erreur interne est survenue',
                'exception'     => $e->getMessage()
            ]);
        }
    }


    /**
     * Compléter le produit avec des informations avant enregistrement
     * 
     * @param   Order       $order
     * @param   string      $mode 
     * 
     * @return Order
     */
    private function completeOrderBeforeSave(Order $order, string $mode) {
        if($mode == 'new'){
            $order->setCreatedAt(new \DateTime());
            $order->setCreatedBy($this->getUser());
        }
        $order->setUpdatedAt(new \DateTime());
        $order->setUpdatedBy($this->getUser());

        return $order;
    }

    /**
     * Enregistrer un produit en base de données
     * 
     * @param   Order       $order
     * @param   string      $mode 
     */
    private function saveOrder(Order $order, string $mode){
        $order = $this->completeOrderBeforeSave($order, $mode);
        
        $em = $this->getDoctrine()->getManager();
        $em->persist($order);
        $em->flush();
    }

}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes{% endblock %}

{% block body %}
    {#{ dump(form) }#}

    {# Titre de la page #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Listing - Commandes</h1>
        </div>
    </div>

    {# Barre de recherche #}
    {{ include('helpers/form/_search.html.twig', { 
                'fields':     ['order_ref'] }) }}

    <div class="container-fluid">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Référence</th>
                    <th scope="col">Prix Total</th>
                    <th scope="col">Créé le</th>
                    <th scope="col">Modifié le</th>
                    <th scope="col">{# Bouton d'action #}</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                <tr>
                    <th scope="row">
                        {{ order.id }}
                    </th>
                    <td>
                        {{ order.reference }}
                    </td>
                    <td>
                        {{ order.totalTtc | replace({'.': ','}) }} €
                    </td>
                    <td>
                        {{ order.createdAt | date("d-m-Y à H:i:s") }}
                    </td>
                    <td>
                        {{ order.updatedAt | date("d-m-Y à H:i:s") }}
                    </td>
                    <td>
                        <a href="{{ path('app_order_detail', {'ref': order.reference}) }}" role="button" class="btn btn-info">Détails</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block stylesheets %}

{% endblock %}

templates/order/liste.html.twig
{% extends 'base.html.twig' %}

{% set total_all = 0 %}

{% block title %}Commandes{% endblock %}

{% block body %}

    {# Titre de la page #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Détails - Commande N°{{ order.reference }}</h1>
        </div>
    </div>

    <div class="container-fluid">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Référence produit</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Quantité</th>
                    <th scope="col">Prix Unitaire</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
                {#{ dump(order) }#}
                {% for product in products %}
                {% set total = product['product'].price * product['quantity'] %}
                {% set total_all = total_all + total %}
                <tr>
                    <td>
                        {{ product['product'].reference }}
                    </td>
                    <td>
                        {{ product['product'].name }}
                    </td>
                    <td>
                        {{ product['quantity'] }}
                    </td>
                    <td>
                        {{ product['product'].price | replace({'.': ','}) }} €
                    </td>
                    <td>
                        {{ total | replace({'.': ','}) }} €
                    </td>
                </tr>
                {% endfor %}

                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <strong>TOTAL À PAYER</strong>
                    </td>
                    <td>
                        <strong>{{ total_all }} €</strong>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}

{% block stylesheets %}

{% endblock %}